# Generated by Django 4.2.3 on 2024-03-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(null=True, upload_to="media/"),
        ),
    ]
