# Generated by Django 4.2.3 on 2024-03-10 23:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("admin", "0005_auto_20230614_1322"),
        ("authentication", "0002_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Account",
        ),
    ]
