# Generated by Django 4.2.3 on 2024-03-13 16:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_rename_account_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
